// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * MZ0380 HDMI signal detection and V4L2 DV-timings operations.
 */

#include <media/v4l2-event.h>

#include "mz0380.h"

/* ===== HDMI signal detect ============================================ */

const struct v4l2_dv_timings mz0380_no_signal = {
	.type = V4L2_DV_BT_656_1120,
};

static const struct v4l2_dv_timings_cap mz0380_timings_cap = {
	.type = V4L2_DV_BT_656_1120,
	.bt = {
		.min_width = 640,
		.max_width = 1920,
		.min_height = 480,
		.max_height = 1080,
		.min_pixelclock = 24000000,
		.max_pixelclock = 297000000,
		.standards = V4L2_DV_BT_STD_CEA861,
		.capabilities = V4L2_DV_BT_CAP_INTERLACED |
				V4L2_DV_BT_CAP_PROGRESSIVE,
	},
};

u32 mz0380_source_fps(const struct v4l2_dv_timings *timings)
{
	const struct v4l2_bt_timings *bt = &timings->bt;
	u64 total = (u64)V4L2_DV_BT_FRAME_WIDTH(bt) *
		    V4L2_DV_BT_FRAME_HEIGHT(bt);

	if (!total || !bt->pixelclock)
		return 0;

	return min_t(u64, 255,
		     div_u64(bt->pixelclock + total / 2, total));
}

/*
 * HDMI signal query. The card never pushes format to the host (RE_FINDINGS.md
 * M6), but the host reads it straight off the MST3367 receiver over the mailbox
 * I2C proxy once the receiver is out of reset (M15). We delegate to
 * mz0380_mst3367_read_signal(), which brings the receiver up on first use, then
 * reads the mode-detect registers and maps the geometry to a v4l2_dv_timings.
 * -ENOLCK = receiver locked to nothing; -ENODEV = firmware not ready.
 */
static int mz0380_query_signal_internal(struct mz0380_dev *dev,
					struct v4l2_dv_timings *out,
					bool allow_cache, bool notify)
{
	/*
	 * M170: remember what we last told userspace, so a change can be
	 * reported as one. mz0380_signal_event() has existed since bring-up
	 * and NOTHING HAS EVER CALLED IT - the source-change event was
	 * generated by dead code, to a subscription the ops table refused to
	 * accept. Both halves are fixed together or neither is worth fixing.
	 *
	 * Normal queries still drive this on demand.  The hotplug worker below
	 * calls the same state transition without the cache, but only after
	 * encoded frames have gone silent; it never adds receiver-I2C traffic to
	 * healthy capture.
	 */
	bool was_locked = dev->signal_locked;
	struct v4l2_dv_timings prev = dev->detected_timings;
	int ret;

	/* Collapse the burst of identical queries made during V4L2 negotiation. */
	if (allow_cache && was_locked && dev->have_last_good &&
	    mz0380_signal_query_cache_ms &&
	    time_before(jiffies, dev->last_good_stamp +
			msecs_to_jiffies(mz0380_signal_query_cache_ms))) {
		*out = dev->detected_timings;
		return 0;
	}

	ret = mz0380_mst3367_read_signal(dev, out);

	if (ret) {
		dev->signal_locked = false;
		dev->detected_timings = mz0380_no_signal;
		dev->capture.source_width = 0;
		dev->capture.source_height = 0;
		dev->capture.source_fps = 0;
		dev->capture.source_interlaced = false;
		*out = mz0380_no_signal;
		if (notify && was_locked && dev->video_registered)
			mz0380_signal_event(dev);
		return ret == -ENODEV ? -ENOLCK : ret;
	}

	if (notify && dev->video_registered &&
	    (!was_locked || !v4l2_match_dv_timings(&prev, out, 250000, false)))
		mz0380_signal_event(dev);

	dev->signal_locked = true;
	dev->detected_timings = *out;
	dev->set_timings = *out;	/* M171: G tracks reality absent an S */
	dev->last_good_timings = *out;      /* M65: survives later failures */
	dev->last_good_stamp = jiffies;
	dev->have_last_good = true;
	dev->capture.source_width = out->bt.width;
	dev->capture.source_height = out->bt.height;
	dev->capture.source_fps = mz0380_source_fps(out);
	dev->capture.source_interlaced = out->bt.interlaced;
	if (dev->capture.source_fps) {
		/* The firmware exposes one whole-frame fps byte; report that cadence. */
		dev->capture.timeperframe.numerator = 1;
		dev->capture.timeperframe.denominator =
			dev->capture.source_fps;
	}
	return 0;
}

int mz0380_query_signal(struct mz0380_dev *dev,
			struct v4l2_dv_timings *out)
{
	return mz0380_query_signal_internal(dev, out, true, true);
}
EXPORT_SYMBOL_GPL(mz0380_query_signal);

void mz0380_signal_event(struct mz0380_dev *dev)
{
	static const struct v4l2_event ev = {
		.type = V4L2_EVENT_SOURCE_CHANGE,
		.u.src_change.changes = V4L2_EVENT_SRC_CH_RESOLUTION,
	};

	v4l2_event_queue(&dev->vdev, &ev);
}
EXPORT_SYMBOL_GPL(mz0380_signal_event);

static bool mz0380_pipeline_matches_signal(struct mz0380_dev *dev,
					    const struct v4l2_dv_timings *live)
{
	return dev->pipeline_source_width == live->bt.width &&
	       dev->pipeline_source_height == live->bt.height &&
	       dev->pipeline_source_fps == mz0380_source_fps(live) &&
	       dev->pipeline_source_interlaced == live->bt.interlaced;
}

/*
 * MST3367 access is proxied through the same firmware mailbox used by stream
 * setup. Do not touch it while the configured H.264 producer is healthy: the
 * hardware has repeatedly made HDMI loss observable as producer silence, and
 * receiver transactions during capture are known to perturb delivery. With no
 * pipeline, during a producer stall, or while validating a reattachment, the
 * worker samples R55 and reserves a complete timing measurement for recovery.
 */
static void mz0380_signal_recovery_work_fn(struct work_struct *work)
{
	struct mz0380_dev *dev = container_of(to_delayed_work(work),
					      struct mz0380_dev,
					      signal_recovery_work);
	struct v4l2_dv_timings live;
	unsigned long retry = msecs_to_jiffies(
		max_t(unsigned int, mz0380_hotplug_retry_ms, 1));
	unsigned long monitor = msecs_to_jiffies(
		max_t(unsigned int, mz0380_signal_monitor_ms, 1));
	unsigned long stall = msecs_to_jiffies(
		max_t(unsigned int, mz0380_hotplug_stall_ms, 1));
	unsigned long last;
	bool locked;
	int ret;

	if (!READ_ONCE(dev->streaming) || !mz0380_hotplug_recovery ||
	    !mz0380_h264_probe) {
		WRITE_ONCE(dev->signal_recovering, false);
		return;
	}

	/*
	 * A live H.264 access unit is the cheapest and strongest steady-state
	 * evidence available. In particular, never let the receiver monitor race
	 * the first GOP immediately after START_STREAMING. Reattachment and active
	 * recovery deliberately bypass this shortcut so one fresh receiver timing
	 * still gates the switch away from the placeholder.
	 */
	last = READ_ONCE(dev->last_h264_frame_stamp);
	if (READ_ONCE(dev->pipeline_running) && last &&
	    !READ_ONCE(dev->signal_recovering) &&
	    !READ_ONCE(dev->pipeline_reconfigure_pending) &&
	    time_before(jiffies, last + stall))
		goto reschedule_monitor;

	ret = mz0380_mst3367_read_lock(dev, &locked, false);
	if (!READ_ONCE(dev->streaming))
		return;
	if (ret) {
		pr_info_ratelimited("%s: HDMI lock monitor read failed (%d)\n",
				    dev->name, ret);
		goto reschedule_retry;
	}

	if (!locked) {
		bool first_loss = !READ_ONCE(dev->signal_recovering) ||
				  !dev->signal_recovery_attempts;

		dev->signal_locked = false;
		dev->detected_timings = mz0380_no_signal;
		dev->capture.source_width = 0;
		dev->capture.source_height = 0;
		dev->capture.source_fps = 0;
		dev->capture.source_interlaced = false;
		mz0380_no_signal_activate(dev,
			READ_ONCE(dev->pipeline_running) ?
			"receiver lock lost; persistent encoder kept alive" :
			"waiting for the first stable HDMI source");

		if (first_loss) {
			WRITE_ONCE(dev->signal_recovering, true);
			dev->signal_recovery_attempts = 0;
			/* This write is allowed only through signal_recovering. */
			ret = mz0380_mst3367_read_lock(dev, &locked, true);
			if (ret)
				pr_info_ratelimited("%s: HDMI acquisition re-arm failed (%d)\n",
						    dev->name, ret);
			dev_info(&dev->pci->dev,
				 "HDMI receiver unlocked; acquisition re-armed, card pipeline %s\n",
				 READ_ONCE(dev->pipeline_running) ?
				 "continues draining/ACKing" : "not spawned");
		}
		dev->signal_recovery_attempts++;
		goto reschedule_retry;
	}

	/*
	 * Receiver R55 can remain fully asserted with coherent but stale timing
	 * registers even though no H.264 access unit exists. Lock and producer
	 * activity are therefore complementary checks: either an explicit unlock
	 * or a configured pipeline which has been silent for the stall interval
	 * enters placeholder recovery. Once a producer exists, its silence gates
	 * these mailbox-backed reads so receiver monitoring cannot perturb healthy
	 * encoded delivery.
	 */
	if (READ_ONCE(dev->pipeline_running) && last &&
	    time_after_eq(jiffies, last + stall) &&
	    !READ_ONCE(dev->signal_recovering)) {
		bool was_placeholder = READ_ONCE(dev->no_signal_active);

		mz0380_no_signal_activate(dev,
			"receiver reports lock but the H.264 producer is silent");
		WRITE_ONCE(dev->signal_recovering, true);
		WRITE_ONCE(dev->h264_waiting_for_idr, true);
		dev->signal_recovery_attempts = 0;
		ret = mz0380_mst3367_read_lock(dev, &locked, true);
		if (ret)
			pr_info_ratelimited("%s: silent-pipeline HDMI acquisition re-arm failed (%d)\n",
					    dev->name, ret);
		if (!was_placeholder)
			dev_warn(&dev->pci->dev,
				 "H.264 producer silent for %ums despite receiver lock; showing NO SIGNAL and forcing HDMI reacquisition\n",
				 jiffies_to_msecs(jiffies - last));
		goto reschedule_retry;
	}

	/* A healthy configured pipeline needs no full multi-register read. */
	if (!READ_ONCE(dev->signal_recovering) &&
	    READ_ONCE(dev->pipeline_running) &&
	    !READ_ONCE(dev->pipeline_reconfigure_pending))
		goto reschedule_monitor;
	if (!READ_ONCE(dev->signal_recovering) &&
	    !READ_ONCE(dev->pipeline_running) &&
	    (READ_ONCE(dev->pipeline_start_failed) ||
	     READ_ONCE(dev->pipeline_reconfigure_pending)))
		goto reschedule_monitor;

	dev->signal_recovery_attempts++;
	ret = mz0380_query_signal_internal(dev, &live, false, false);
	if (!READ_ONCE(dev->streaming))
		return;
	if (ret) {
		pr_info_ratelimited("%s: HDMI full lock appeared but stable timing is not ready on attempt %u (%d)\n",
				    dev->name, dev->signal_recovery_attempts, ret);
		goto reschedule_retry;
	}

	if (!READ_ONCE(dev->pipeline_running)) {
		if (mz0380_strict_geometry &&
		    (live.bt.width != dev->capture.width ||
		     live.bt.height != dev->capture.height)) {
			WRITE_ONCE(dev->pipeline_reconfigure_pending, true);
			if (dev->video_registered)
				mz0380_signal_event(dev);
			dev_warn(&dev->pci->dev,
				 "stable HDMI source is %ux%u but VB2 is %ux%u; keeping NO SIGNAL until userspace renegotiates\n",
				 live.bt.width, live.bt.height, dev->capture.width,
				 dev->capture.height);
			WRITE_ONCE(dev->signal_recovering, false);
			goto reschedule_monitor;
		}
		if (READ_ONCE(dev->pipeline_start_failed)) {
			WRITE_ONCE(dev->signal_recovering, false);
			goto reschedule_monitor;
		}

		WRITE_ONCE(dev->h264_waiting_for_idr, true);
		WRITE_ONCE(dev->last_h264_frame_stamp, jiffies);
		ret = mz0380_dma_start(dev);
		if (!READ_ONCE(dev->streaming))
			return;
		if (ret) {
			WRITE_ONCE(dev->pipeline_start_failed, true);
			dev_err(&dev->pci->dev,
				"stable HDMI lock found but deferred pipeline start failed (%d); NO SIGNAL remains active and no automatic respawn will be attempted\n",
				ret);
			WRITE_ONCE(dev->signal_recovering, false);
			goto reschedule_monitor;
		}
		dev_info(&dev->pci->dev,
			 "stable HDMI lock %ux%u%c@%u started the first card pipeline with one SET_VIC; holding NO SIGNAL until clean live IDR\n",
			 live.bt.width, live.bt.height,
			 live.bt.interlaced ? 'i' : 'p',
			 mz0380_source_fps(&live));
		WRITE_ONCE(dev->signal_recovering, false);
		goto reschedule_monitor;
	}

	if (!mz0380_pipeline_matches_signal(dev, &live)) {
		bool already_pending =
			READ_ONCE(dev->pipeline_reconfigure_pending);

		WRITE_ONCE(dev->pipeline_reconfigure_pending, true);
		if (!already_pending && dev->video_registered)
			mz0380_signal_event(dev);
		dev_info(&dev->pci->dev,
			 "HDMI lock returned as %ux%u%c@%u, different from persistent %ux%u%c@%u; NO SIGNAL remains until one controlled replacement at the next attachment%s\n",
			 live.bt.width, live.bt.height,
			 live.bt.interlaced ? 'i' : 'p',
			 mz0380_source_fps(&live),
			 dev->pipeline_source_width,
			 dev->pipeline_source_height,
			 dev->pipeline_source_interlaced ? 'i' : 'p',
			 dev->pipeline_source_fps,
			 already_pending ? " (already pending)" : "");
		WRITE_ONCE(dev->signal_recovering, false);
		goto reschedule_monitor;
	}

	/*
	 * A reconnect can expose a transient timing while the source negotiates
	 * (the hardware run measured 1080p60 between two stable 1080p30 reads).
	 * If that transient queued a replacement but the receiver subsequently
	 * returns to the pipeline's original mode, cancel the stale request.  The
	 * old latch otherwise suppresses every healthy live IDR forever while the
	 * producer continues running, making a live card look frozen on NO SIGNAL.
	 * Keep polling while replacement is pending (the shortcuts above exclude
	 * it) so this cancellation is reachable without a userspace reattachment.
	 */
	if (READ_ONCE(dev->pipeline_reconfigure_pending)) {
		WRITE_ONCE(dev->pipeline_reconfigure_pending, false);
		dev_info(&dev->pci->dev,
			 "HDMI timing returned to persistent %ux%u%c@%u; cancelled transient replacement, holding NO SIGNAL only until clean live IDR\n",
			 dev->pipeline_source_width, dev->pipeline_source_height,
			 dev->pipeline_source_interlaced ? 'i' : 'p',
			 dev->pipeline_source_fps);
	}

	dev_info(&dev->pci->dev,
		 "HDMI reconnect lock on recovery attempt %u: %ux%u%c@%u; persistent encoder unchanged, holding NO SIGNAL until clean live IDR\n",
		 dev->signal_recovery_attempts, live.bt.width, live.bt.height,
		 live.bt.interlaced ? 'i' : 'p', mz0380_source_fps(&live));
	WRITE_ONCE(dev->h264_waiting_for_idr, true);
	WRITE_ONCE(dev->signal_recovering, false);

reschedule_monitor:
	if (READ_ONCE(dev->streaming))
		mod_delayed_work(MZ0380_SYSTEM_WQ, &dev->signal_recovery_work,
				 monitor);
	return;

reschedule_retry:
	if (READ_ONCE(dev->streaming))
		mod_delayed_work(MZ0380_SYSTEM_WQ, &dev->signal_recovery_work,
				 retry);
	return;
}

void mz0380_signal_recovery_init(struct mz0380_dev *dev)
{
	INIT_DELAYED_WORK(&dev->signal_recovery_work,
			  mz0380_signal_recovery_work_fn);
}

void mz0380_signal_recovery_start(struct mz0380_dev *dev)
{
	if (!mz0380_hotplug_recovery || !mz0380_h264_probe ||
	    mz0380_stream_nosg)
		return;

	dev->signal_recovery_attempts = 0;
	WRITE_ONCE(dev->h264_waiting_for_idr, true);
	WRITE_ONCE(dev->last_h264_frame_stamp, jiffies);
	mod_delayed_work(MZ0380_SYSTEM_WQ, &dev->signal_recovery_work, 0);
}

void mz0380_signal_recovery_stop(struct mz0380_dev *dev)
{
	cancel_delayed_work_sync(&dev->signal_recovery_work);
	mz0380_no_signal_stop(dev);
	WRITE_ONCE(dev->signal_recovering, false);
	WRITE_ONCE(dev->h264_waiting_for_idr, false);
}

int mz0380_query_dv_timings(struct file *file, void *fh,
				   struct v4l2_dv_timings *t)
{
	struct mz0380_dev *dev = video_drvdata(file);

	/*
	 * Do not drive the receiver's serialized mailbox-I2C path while video is
	 * flowing. OBS may issue QUERY_DV_TIMINGS periodically from the same side
	 * that dequeues capture buffers; a live measurement stalls that recycling
	 * long enough to exhaust the vb2 queue. During placeholder-only streaming
	 * the independent worker owns receiver discovery; after the encoder starts
	 * it cannot adopt changed geometry without a new configuration. In both
	 * cases userspace gets cached lock state. ENUM_INPUT follows the same rule.
	 */
	if (READ_ONCE(dev->streaming) || READ_ONCE(dev->pipeline_running)) {
		if (!dev->signal_locked || !dev->have_last_good) {
			*t = mz0380_no_signal;
			return -ENOLCK;
		}
		*t = dev->detected_timings;
		return 0;
	}

	return mz0380_query_signal(dev, t);
}

/*
 * M171: G returns what was SET, QUERY returns what is DETECTED.
 *
 * Both used to answer with the live detection, and S_DV_TIMINGS was a comment
 * saying "no-op-but-validate" that neither noted nor validated. So
 * S_DV_TIMINGS(x) followed by G_DV_TIMINGS returned something else entirely,
 * which is what v4l2-compliance reported as
 * "g_timings.bt.width != enumtimings.timings.bt.width".
 *
 * The card does auto-detect and nothing host-side changes what it receives, so
 * the set value does not steer the hardware - stream start uses the detection.
 * But the ioctl contract is still a contract, and a successful detection
 * updates the set value too, so G tracks reality for anyone who never calls S.
 */
int mz0380_g_dv_timings(struct file *file, void *fh,
			       struct v4l2_dv_timings *t)
{
	struct mz0380_dev *dev = video_drvdata(file);

	*t = dev->set_timings;
	return 0;
}

int mz0380_s_dv_timings(struct file *file, void *fh,
			       struct v4l2_dv_timings *t)
{
	struct mz0380_dev *dev = video_drvdata(file);
	const struct mz0380_mode *mode;
	const struct v4l2_fract *interval;

	if (!v4l2_valid_dv_timings(t, &mz0380_timings_cap, NULL, NULL))
		return -EINVAL;

	/*
	 * M172: busy only blocks a CHANGE.
	 *
	 * A bare vb2_is_busy() test failed v4l2-compliance's
	 * testCanSetSameTimings: it allocates buffers and then sets the timings
	 * it already has, which must succeed because nothing about the buffers
	 * is invalidated by setting a value to itself. -EBUSY is for the case
	 * where the new timings would resize the format out from under
	 * allocated buffers.
	 */
	if (vb2_is_busy(&dev->vb_queue) &&
	    !v4l2_match_dv_timings(&dev->set_timings, t, 0, false))
		return -EBUSY;

	dev->set_timings = *t;

	/*
	 * M172: and the format follows the timings.
	 *
	 * v4l2-compliance caught this as
	 * "fmt.fmt.pix.width >= enumtimings.timings.bt.width * 1.5" - it set a
	 * small timing, asked for the format, and was still told 1920x1080,
	 * because S_DV_TIMINGS touched nothing but its own stored copy.
	 *
	 * For an HDMI receiver the capture format IS the source geometry; there
	 * is no scaler on this path, and the delivered frame is exactly
	 * width*height*3/2 of I420. So a client that declares the incoming
	 * timings must get a format that matches them, snapped to a mode this
	 * driver supports.
	 */
	mode = mz0380_find_mode(t->bt.width, t->bt.height);
	interval = mz0380_find_interval(mode->width, mode->height,
					&dev->capture.timeperframe);
	dev->capture.width = mode->width;
	dev->capture.height = mode->height;
	dev->capture.timeperframe = *interval;

	return 0;
}

int mz0380_enum_dv_timings(struct file *file, void *fh,
				  struct v4l2_enum_dv_timings *t)
{
	return v4l2_enum_dv_timings_cap(t, &mz0380_timings_cap, NULL, NULL);
}

int mz0380_dv_timings_cap(struct file *file, void *fh,
				 struct v4l2_dv_timings_cap *cap)
{
	*cap = mz0380_timings_cap;
	return 0;
}
